import { StairTransition } from '@/components/StairTransition';
import {JetBrains_Mono, Oregano} from "next/font/google"
import "./globals.css";
import "./globals.scss";

// Components
import {Header} from "@/components/Header";
import { PageTransition } from '@/components/PageTransition';

const jetbrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	weight: ['100', '200', '300', "400", "500", "600", "700", "800"],
	variable: "--font-jetbrainsMono",
})

const oregano = Oregano({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-oregano",
})

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}) {
	return (
		<html lang="en" className="scroll-smooth">
		<body
			className={`${jetbrainsMono.variable} ${oregano.variable}`}
		>
		<Header/>
		<StairTransition />
		<PageTransition>
			{children}
		</PageTransition>
		</body>
		</html>
	);
}
